# Generated by Django 3.2.10 on 2024-07-06 22:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20240707_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, null=True, verbose_name='Новостройка'),
        )
    ]
