# Generated by Django 3.2.10 on 2024-07-06 23:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20240707_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU'),
        ),
    ]
