# Generated by Django 3.2.10 on 2024-07-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_flat_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='phonenumber',
            new_name='owner_pure_phone',
        ),
    ]
