# Generated by Django 3.2.24 on 2024-09-26 15:20

from django.db import migrations

from phonenumbers import parse
from phonenumbers import is_valid_number


def parse_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        num = parse(flat.owners_phonenumber, 'RU')
        if is_valid_number(num):
            flat.owner_pure_phone = num
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20240926_1819'),
    ]

    operations = [
        migrations.RunPython(parse_phonenumber)
    ]
