# Generated by Django 3.2.24 on 2024-10-01 13:49

from django.db import migrations

def connect_owner_and_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for obj in list(Owner.objects.all()):
        list_ = list(Flat.objects.filter(owner_pure_phone=obj.pure_phonenumber))
        obj.flats.set(list_)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20241001_1642'),
    ]

    operations = [
        migrations.RunPython(connect_owner_and_flat)
    ]
