# Generated by Django 3.2.10 on 2024-07-16 16:53

from django.db import migrations


def connect_owner_and_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for obj in list(Owner.objects.all()):
        list_ = list(Flat.objects.filter(owner_pure_phone=obj.pure_phonenumber))
        obj.flats.set(list_)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_owner_flats'),
    ]

    operations = [
        migrations.RunPython(connect_owner_and_flat)
    ]
