# Generated by Django 3.2.10 on 2024-06-16 22:26

from django.db import migrations


def define_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for obj in list(Flat.objects.all()):
        if obj.construction_year >= 2015:
            obj.new_building = True
        else:
            obj.new_building = False
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20240617_0117'),
    ]

    operations = [
        migrations.RunPython(define_new_building)
    ]
